name: news_getter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc_concurrency: ^0.2.1
  equatable: ^2.0.5
  
  flutter_bloc: ^8.1.2
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.0.20
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4

  google_sign_in: ^5.2.1
  email_validator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
